### ISSUE TITLE
laravel-repository does not support laravel 10? could not upgrade to laravel 10. 

### ISSUE THREAD

**Issue by bhojkamal** [JoBinsJP/laravel-repository#23]
Hello, 
I tried to upgrade my project to Laravel 10 but this package does not allow me to upgrade throwing the following error. Can you please make compatible with Laravel 10 as earlier as possible? 
Error screenshots are below:
![image](https://user-images.githubusercontent.com/14083299/226158373-bcd1fc84-528d-434b-9d35-7679c29b1afd.png)

![image](https://user-images.githubusercontent.com/14083299/226158394-7b8f3f5b-c526-447f-a653-6e8f3ff235c0.png)

Best Regards,
Kamal

**Comment by bedus-creation** [comment]
Sorry for the Late reply, I think the recent release should support Laravel 10.x
